[project]
name="fantasy_football"
version="1.0.0.0"
requires-python="<=3.1.0"
dependencies =[
    "nfl_data_py~=0.3.3",
    "pandas~=1.5.3"
]

[pyprojct.optional-dependencies]
dev = [
    #pytest
]

[build-system]
requires = [
    "setuptools<=6.1.0",
    "wheel>=0.45.1"
]

build-backend="setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]